export const materialIcons = [
  { icon: '3d_rotation', name: '3d rotation icon' },
  { icon: 'accessibility', name: 'accessibility icon' },
  { icon: 'accessibility_new', name: 'accessibility new icon' },
  { icon: 'accessible', name: 'accessible icon' },
  { icon: 'accessible_forward', name: 'accessible forward icon' },
  { icon: 'account_balance', name: 'account balance icon' },
  { icon: 'account_balance_wallet', name: 'account balance wallet icon' },
  { icon: 'account_box', name: 'account box icon' },
  { icon: 'account_circle', name: 'account circle icon' },
  { icon: 'add_shopping_cart', name: 'add shopping cart icon' },
  { icon: 'alarm', name: 'alarm icon' },
  { icon: 'alarm_add', name: 'alarm add icon' },
  { icon: 'alarm_off', name: 'alarm off icon' },
  { icon: 'alarm_on', name: 'alarm on icon' },
  { icon: 'all_out', name: 'all out icon' },
  { icon: 'android', name: 'android icon' },
  { icon: 'announcement', name: 'announcement icon' },
  { icon: 'arrow_right_alt', name: 'arrow right alt icon' },
  { icon: 'aspect_ratio', name: 'aspect ratio icon' },
  { icon: 'assessment', name: 'assessment icon' },
  { icon: 'assignment', name: 'assignment icon' },
  { icon: 'assignment_ind', name: 'assignment ind icon' },
  { icon: 'assignment_late', name: 'assignment late icon' },
  { icon: 'assignment_return', name: 'assignment return icon' },
  { icon: 'assignment_returned', name: 'assignment returned icon' },
  { icon: 'assignment_turned_in', name: 'assignment turned in icon' },
  { icon: 'autorenew', name: 'autorenew icon' },
  { icon: 'backup', name: 'backup icon' },
  { icon: 'book', name: 'book icon' },
  { icon: 'bookmark', name: 'bookmark icon' },
  { icon: 'bookmark_border', name: 'bookmark border icon' },
  { icon: 'bug_report', name: 'bug report icon' },
  { icon: 'build', name: 'build icon' },
  { icon: 'cached', name: 'cached icon' },
  { icon: 'calendar_today', name: 'calendar today icon' },
  { icon: 'calendar_view_day', name: 'calendar view day icon' },
  { icon: 'camera_enhance', name: 'camera enhance icon' },
  { icon: 'card_giftcard', name: 'card giftcard icon' },
  { icon: 'card_membership', name: 'card membership icon' },
  { icon: 'card_travel', name: 'card travel icon' },
  { icon: 'change_history', name: 'change history icon' },
  { icon: 'check_circle', name: 'check circle icon' },
  { icon: 'check_circle_outline', name: 'check circle outline icon' },
  { icon: 'chrome_reader_mode', name: 'chrome reader mode icon' },
  { icon: 'class', name: 'class icon' },
  { icon: 'code', name: 'code icon' },
  { icon: 'commute', name: 'commute icon' },
  { icon: 'compare_arrows', name: 'compare arrows icon' },
  { icon: 'contact_support', name: 'contact support icon' },
  { icon: 'copyright', name: 'copyright icon' },
  { icon: 'credit_card', name: 'credit card icon' },
  { icon: 'dashboard', name: 'dashboard icon' },
  { icon: 'date_range', name: 'date range icon' },
  { icon: 'delete', name: 'delete icon' },
  { icon: 'delete_forever', name: 'delete forever icon' },
  { icon: 'delete_outline', name: 'delete outline icon' },
  { icon: 'description', name: 'description icon' },
  { icon: 'dns', name: 'dns icon' },
  { icon: 'done', name: 'done icon' },
  { icon: 'done_all', name: 'done all icon' },
  { icon: 'done_outline', name: 'done outline icon' },
  { icon: 'donut_large', name: 'donut large icon' },
  { icon: 'donut_small', name: 'donut small icon' },
  { icon: 'drag_indicator', name: 'drag indicator icon' },
  { icon: 'eject', name: 'eject icon' },
  { icon: 'euro_symbol', name: 'euro symbol icon' },
  { icon: 'event', name: 'event icon' },
  { icon: 'event_seat', name: 'event seat icon' },
  { icon: 'exit_to_app', name: 'exit to app icon' },
  { icon: 'explore', name: 'explore icon' },
  { icon: 'extension', name: 'extension icon' },
  { icon: 'face', name: 'face icon' },
  { icon: 'favorite', name: 'favorite icon' },
  { icon: 'favorite_border', name: 'favorite border icon' },
  { icon: 'feedback', name: 'feedback icon' },
  { icon: 'find_in_page', name: 'find in page icon' },
  { icon: 'find_replace', name: 'find replace icon' },
  { icon: 'fingerprint', name: 'fingerprint icon' },
  { icon: 'flight_land', name: 'flight land icon' },
  { icon: 'flight_takeoff', name: 'flight takeoff icon' },
  { icon: 'flip_to_back', name: 'flip to back icon' },
  { icon: 'flip_to_front', name: 'flip to front icon' },
  { icon: 'g_translate', name: 'g translate icon' },
  { icon: 'gavel', name: 'gavel icon' },
  { icon: 'get_app', name: 'get app icon' },
  { icon: 'gif', name: 'gif icon' },
  { icon: 'grade', name: 'grade icon' },
  { icon: 'group_work', name: 'group work icon' },
  { icon: 'help', name: 'help icon' },
  { icon: 'help_outline', name: 'help outline icon' },
  { icon: 'highlight_off', name: 'highlight off icon' },
  { icon: 'history', name: 'history icon' },
  { icon: 'home', name: 'home icon' },
  { icon: 'horizontal_split', name: 'horizontal split icon' },
  { icon: 'hourglass_empty', name: 'hourglass empty icon' },
  { icon: 'hourglass_full', name: 'hourglass full icon' },
  { icon: 'http', name: 'http icon' },
  { icon: 'https', name: 'https icon' },
  { icon: 'important_devices', name: 'important devices icon' },
  { icon: 'info', name: 'info icon' },
  { icon: 'input', name: 'input icon' },
  { icon: 'invert_colors', name: 'invert colors icon' },
  { icon: 'label', name: 'label icon' },
  { icon: 'label_important', name: 'label important icon' },
  { icon: 'language', name: 'language icon' },
  { icon: 'launch', name: 'launch icon' },
  { icon: 'line_style', name: 'line style icon' },
  { icon: 'line_weight', name: 'line weight icon' },
  { icon: 'list', name: 'list icon' },
  { icon: 'lock', name: 'lock icon' },
  { icon: 'lock_open', name: 'lock open icon' },
  { icon: 'loyalty', name: 'loyalty icon' },
  { icon: 'markunread_mailbox', name: 'markunread mailbox icon' },
  { icon: 'maximize', name: 'maximize icon' },
  { icon: 'minimize', name: 'minimize icon' },
  { icon: 'motorcycle', name: 'motorcycle icon' },
  { icon: 'note_add', name: 'note add icon' },
  { icon: 'offline_bolt', name: 'offline bolt icon' },
  { icon: 'offline_pin', name: 'offline pin icon' },
  { icon: 'opacity', name: 'opacity icon' },
  { icon: 'open_in_browser', name: 'open in browser icon' },
  { icon: 'open_in_new', name: 'open in new icon' },
  { icon: 'open_with', name: 'open with icon' },
  { icon: 'pageview', name: 'pageview icon' },
  { icon: 'pan_tool', name: 'pan tool icon' },
  { icon: 'payment', name: 'payment icon' },
  { icon: 'perm_camera_mic', name: 'perm camera mic icon' },
  { icon: 'perm_contact_calendar', name: 'perm contact calendar icon' },
  { icon: 'perm_data_setting', name: 'perm data setting icon' },
  { icon: 'perm_device_information', name: 'perm device information icon' },
  { icon: 'perm_identity', name: 'perm identity icon' },
  { icon: 'perm_media', name: 'perm media icon' },
  { icon: 'perm_phone_msg', name: 'perm phone msg icon' },
  { icon: 'perm_scan_wifi', name: 'perm scan wifi icon' },
  { icon: 'pets', name: 'pets icon' },
  { icon: 'picture_in_picture', name: 'picture in picture icon' },
  { icon: 'picture_in_picture_alt', name: 'picture in picture alt icon' },
  { icon: 'play_for_work', name: 'play for work icon' },
  { icon: 'polymer', name: 'polymer icon' },
  { icon: 'power_settings_new', name: 'power settings new icon' },
  { icon: 'pregnant_woman', name: 'pregnant woman icon' },
  { icon: 'print', name: 'print icon' },
  { icon: 'query_builder', name: 'query builder icon' },
  { icon: 'question_answer', name: 'question answer icon' },
  { icon: 'receipt', name: 'receipt icon' },
  { icon: 'record_voice_over', name: 'record voice over icon' },
  { icon: 'redeem', name: 'redeem icon' },
  { icon: 'remove_shopping_cart', name: 'remove shopping cart icon' },
  { icon: 'reorder', name: 'reorder icon' },
  { icon: 'report_problem', name: 'report problem icon' },
  { icon: 'restore', name: 'restore icon' },
  { icon: 'restore_from_trash', name: 'restore from trash icon' },
  { icon: 'restore_page', name: 'restore page icon' },
  { icon: 'room', name: 'room icon' },
  { icon: 'rounded_corner', name: 'rounded corner icon' },
  { icon: 'rowing', name: 'rowing icon' },
  { icon: 'schedule', name: 'schedule icon' },
  { icon: 'search', name: 'search icon' },
  { icon: 'settings', name: 'settings icon' },
  { icon: 'settings_applications', name: 'settings applications icon' },
  { icon: 'settings_backup_restore', name: 'settings backup restore icon' },
  { icon: 'settings_bluetooth', name: 'settings bluetooth icon' },
  { icon: 'settings_brightness', name: 'settings brightness icon' },
  { icon: 'settings_cell', name: 'settings cell icon' },
  { icon: 'settings_ethernet', name: 'settings ethernet icon' },
  { icon: 'settings_input_antenna', name: 'settings input antenna icon' },
  { icon: 'settings_input_component', name: 'settings input component icon' },
  { icon: 'settings_input_composite', name: 'settings input composite icon' },
  { icon: 'settings_input_hdmi', name: 'settings input hdmi icon' },
  { icon: 'settings_input_svideo', name: 'settings input svideo icon' },
  { icon: 'settings_overscan', name: 'settings overscan icon' },
  { icon: 'settings_phone', name: 'settings phone icon' },
  { icon: 'settings_power', name: 'settings power icon' },
  { icon: 'settings_remote', name: 'settings remote icon' },
  { icon: 'settings_voice', name: 'settings voice icon' },
  { icon: 'shop', name: 'shop icon' },
  { icon: 'shop_two', name: 'shop two icon' },
  { icon: 'shopping_basket', name: 'shopping basket icon' },
  { icon: 'shopping_cart', name: 'shopping cart icon' },
  { icon: 'speaker_notes', name: 'speaker notes icon' },
  { icon: 'speaker_notes_off', name: 'speaker notes off icon' },
  { icon: 'spellcheck', name: 'spellcheck icon' },
  { icon: 'stars', name: 'stars icon' },
  { icon: 'store', name: 'store icon' },
  { icon: 'subject', name: 'subject icon' },
  { icon: 'supervised_user_circle', name: 'supervised user circle icon' },
  { icon: 'supervisor_account', name: 'supervisor account icon' },
  { icon: 'swap_horiz', name: 'swap horiz icon' },
  { icon: 'swap_horizontal_circle', name: 'swap horizontal circle icon' },
  { icon: 'swap_vert', name: 'swap vert icon' },
  { icon: 'swap_vertical_circle', name: 'swap vertical circle icon' },
  { icon: 'tab', name: 'tab icon' },
  { icon: 'tab_unselected', name: 'tab unselected icon' },
  { icon: 'text_rotate_up', name: 'text rotate up icon' },
  { icon: 'text_rotate_vertical', name: 'text rotate vertical icon' },
  { icon: 'text_rotation_down', name: 'text rotation down icon' },
  { icon: 'text_rotation_none', name: 'text rotation none icon' },
  { icon: 'theaters', name: 'theaters icon' },
  { icon: 'thumb_down', name: 'thumb down icon' },
  { icon: 'thumb_up', name: 'thumb up icon' },
  { icon: 'thumbs_up_down', name: 'thumbs up down icon' },
  { icon: 'timeline', name: 'timeline icon' },
  { icon: 'toc', name: 'toc icon' },
  { icon: 'today', name: 'today icon' },
  { icon: 'toll', name: 'toll icon' },
  { icon: 'touch_app', name: 'touch app icon' },
  { icon: 'track_changes', name: 'track changes icon' },
  { icon: 'translate', name: 'translate icon' },
  { icon: 'trending_down', name: 'trending down icon' },
  { icon: 'trending_flat', name: 'trending flat icon' },
  { icon: 'trending_up', name: 'trending up icon' },
  { icon: 'turned_in', name: 'turned in icon' },
  { icon: 'turned_in_not', name: 'turned in not icon' },
  { icon: 'update', name: 'update icon' },
  { icon: 'verified_user', name: 'verified user icon' },
  { icon: 'vertical_split', name: 'vertical split icon' },
  { icon: 'view_agenda', name: 'view agenda icon' },
  { icon: 'view_array', name: 'view array icon' },
  { icon: 'view_carousel', name: 'view carousel icon' },
  { icon: 'view_column', name: 'view column icon' },
  { icon: 'view_day', name: 'view day icon' },
  { icon: 'view_headline', name: 'view headline icon' },
  { icon: 'view_list', name: 'view list icon' },
  { icon: 'view_module', name: 'view module icon' },
  { icon: 'view_quilt', name: 'view quilt icon' },
  { icon: 'view_stream', name: 'view stream icon' },
  { icon: 'view_week', name: 'view week icon' },
  { icon: 'visibility', name: 'visibility icon' },
  { icon: 'visibility_off', name: 'visibility off icon' },
  { icon: 'voice_over_off', name: 'voice over off icon' },
  { icon: 'watch_later', name: 'watch later icon' },
  { icon: 'work', name: 'work icon' },
  { icon: 'work_off', name: 'work off icon' },
  { icon: 'work_outline', name: 'work outline icon' },
  { icon: 'youtube_searched_for', name: 'youtube searched for icon' },
  { icon: 'zoom_in', name: 'zoom in icon' },
  { icon: 'zoom_out', name: 'zoom out icon' },
  { icon: 'alternate_email', name: 'alternate email icon' },
  { icon: 'business', name: 'business icon' },
  { icon: 'call', name: 'call icon' },
  { icon: 'call_end', name: 'call end icon' },
  { icon: 'call_made', name: 'call made icon' },
  { icon: 'call_merge', name: 'call merge icon' },
  { icon: 'call_missed', name: 'call missed icon' },
  { icon: 'call_missed_outgoing', name: 'call missed outgoing icon' },
  { icon: 'call_received', name: 'call received icon' },
  { icon: 'call_split', name: 'call split icon' },
  { icon: 'cancel_presentation', name: 'cancel presentation icon' },
  { icon: 'cell_wifi', name: 'cell wifi icon' },
  { icon: 'chat', name: 'chat icon' },
  { icon: 'chat_bubble', name: 'chat bubble icon' },
  { icon: 'chat_bubble_outline', name: 'chat bubble outline icon' },
  { icon: 'clear_all', name: 'clear all icon' },
  { icon: 'comment', name: 'comment icon' },
  { icon: 'contact_mail', name: 'contact mail icon' },
  { icon: 'contact_phone', name: 'contact phone icon' },
  { icon: 'contacts', name: 'contacts icon' },
  { icon: 'dialer_sip', name: 'dialer sip icon' },
  { icon: 'dialpad', name: 'dialpad icon' },
  { icon: 'domain_disabled', name: 'domain disabled icon' },
  { icon: 'email', name: 'email icon' },
  { icon: 'forum', name: 'forum icon' },
  { icon: 'import_contacts', name: 'import contacts icon' },
  { icon: 'import_export', name: 'import export icon' },
  { icon: 'invert_colors_off', name: 'invert colors off icon' },
  { icon: 'list_alt', name: 'list alt icon' },
  { icon: 'live_help', name: 'live help icon' },
  { icon: 'location_off', name: 'location off icon' },
  { icon: 'location_on', name: 'location on icon' },
  { icon: 'mail_outline', name: 'mail outline icon' },
  { icon: 'message', name: 'message icon' },
  { icon: 'mobile_screen_share', name: 'mobile screen share icon' },
  { icon: 'no_sim', name: 'no sim icon' },
  { icon: 'pause_presentation', name: 'pause presentation icon' },
  { icon: 'phone', name: 'phone icon' },
  { icon: 'phonelink_erase', name: 'phonelink erase icon' },
  { icon: 'phonelink_lock', name: 'phonelink lock icon' },
  { icon: 'phonelink_ring', name: 'phonelink ring icon' },
  { icon: 'phonelink_setup', name: 'phonelink setup icon' },
  { icon: 'portable_wifi_off', name: 'portable wifi off icon' },
  { icon: 'present_to_all', name: 'present to all icon' },
  { icon: 'ring_volume', name: 'ring volume icon' },
  { icon: 'rss_feed', name: 'rss feed icon' },
  { icon: 'screen_share', name: 'screen share icon' },
  { icon: 'sentiment_satisfied_alt', name: 'sentiment satisfied alt icon' },
  { icon: 'speaker_phone', name: 'speaker phone icon' },
  { icon: 'stay_current_landscape', name: 'stay current landscape icon' },
  { icon: 'stay_current_portrait', name: 'stay current portrait icon' },
  { icon: 'stay_primary_landscape', name: 'stay primary landscape icon' },
  { icon: 'stay_primary_portrait', name: 'stay primary portrait icon' },
  { icon: 'stop_screen_share', name: 'stop screen share icon' },
  { icon: 'swap_calls', name: 'swap calls icon' },
  { icon: 'textsms', name: 'textsms icon' },
  { icon: 'unsubscribe', name: 'unsubscribe icon' },
  { icon: 'voicemail', name: 'voicemail icon' },
  { icon: 'vpn_key', name: 'vpn key icon' },
  { icon: '4k', name: '4k icon' },
  { icon: 'add_to_queue', name: 'add to queue icon' },
  { icon: 'airplay', name: 'airplay icon' },
  { icon: 'album', name: 'album icon' },
  { icon: 'art_track', name: 'art track icon' },
  { icon: 'av_timer', name: 'av timer icon' },
  { icon: 'branding_watermark', name: 'branding watermark icon' },
  { icon: 'call_to_action', name: 'call to action icon' },
  { icon: 'closed_caption', name: 'closed caption icon' },
  { icon: 'control_camera', name: 'control camera icon' },
  { icon: 'equalizer', name: 'equalizer icon' },
  { icon: 'explicit', name: 'explicit icon' },
  { icon: 'fast_forward', name: 'fast forward icon' },
  { icon: 'fast_rewind', name: 'fast rewind icon' },
  { icon: 'featured_play_list', name: 'featured play list icon' },
  { icon: 'featured_video', name: 'featured video icon' },
  { icon: 'fiber_dvr', name: 'fiber dvr icon' },
  { icon: 'fiber_manual_record', name: 'fiber manual record icon' },
  { icon: 'fiber_new', name: 'fiber new icon' },
  { icon: 'fiber_pin', name: 'fiber pin icon' },
  { icon: 'fiber_smart_record', name: 'fiber smart record icon' },
  { icon: 'forward_10', name: 'forward 10 icon' },
  { icon: 'forward_30', name: 'forward 30 icon' },
  { icon: 'forward_5', name: 'forward 5 icon' },
  { icon: 'games', name: 'games icon' },
  { icon: 'hd', name: 'hd icon' },
  { icon: 'hearing', name: 'hearing icon' },
  { icon: 'high_quality', name: 'high quality icon' },
  { icon: 'library_add', name: 'library add icon' },
  { icon: 'library_books', name: 'library books icon' },
  { icon: 'library_music', name: 'library music icon' },
  { icon: 'loop', name: 'loop icon' },
  { icon: 'mic', name: 'mic icon' },
  { icon: 'mic_none', name: 'mic none icon' },
  { icon: 'mic_off', name: 'mic off icon' },
  { icon: 'missed_video_call', name: 'missed video call icon' },
  { icon: 'movie', name: 'movie icon' },
  { icon: 'music_video', name: 'music video icon' },
  { icon: 'new_releases', name: 'new releases icon' },
  { icon: 'not_interested', name: 'not interested icon' },
  { icon: 'note', name: 'note icon' },
  { icon: 'pause', name: 'pause icon' },
  { icon: 'pause_circle_filled', name: 'pause circle filled icon' },
  { icon: 'pause_circle_outline', name: 'pause circle outline icon' },
  { icon: 'play_arrow', name: 'play arrow icon' },
  { icon: 'play_circle_filled', name: 'play circle filled icon' },
  { icon: 'play_circle_outline', name: 'play circle outline icon' },
  { icon: 'playlist_add', name: 'playlist add icon' },
  { icon: 'playlist_add_check', name: 'playlist add check icon' },
  { icon: 'playlist_play', name: 'playlist play icon' },
  { icon: 'queue', name: 'queue icon' },
  { icon: 'queue_music', name: 'queue music icon' },
  { icon: 'queue_play_next', name: 'queue play next icon' },
  { icon: 'radio', name: 'radio icon' },
  { icon: 'recent_actors', name: 'recent actors icon' },
  { icon: 'remove_from_queue', name: 'remove from queue icon' },
  { icon: 'repeat', name: 'repeat icon' },
  { icon: 'repeat_one', name: 'repeat one icon' },
  { icon: 'replay', name: 'replay icon' },
  { icon: 'replay_10', name: 'replay 10 icon' },
  { icon: 'replay_30', name: 'replay 30 icon' },
  { icon: 'replay_5', name: 'replay 5 icon' },
  { icon: 'shuffle', name: 'shuffle icon' },
  { icon: 'skip_next', name: 'skip next icon' },
  { icon: 'skip_previous', name: 'skip previous icon' },
  { icon: 'slow_motion_video', name: 'slow motion video icon' },
  { icon: 'snooze', name: 'snooze icon' },
  { icon: 'sort_by_alpha', name: 'sort by alpha icon' },
  { icon: 'stop', name: 'stop icon' },
  { icon: 'subscriptions', name: 'subscriptions icon' },
  { icon: 'subtitles', name: 'subtitles icon' },
  { icon: 'surround_sound', name: 'surround sound icon' },
  { icon: 'video_call', name: 'video call icon' },
  { icon: 'video_label', name: 'video label icon' },
  { icon: 'video_library', name: 'video library icon' },
  { icon: 'videocam', name: 'videocam icon' },
  { icon: 'videocam_off', name: 'videocam off icon' },
  { icon: 'volume_down', name: 'volume down icon' },
  { icon: 'volume_mute', name: 'volume mute icon' },
  { icon: 'volume_off', name: 'volume off icon' },
  { icon: 'add', name: 'add icon' },
  { icon: 'add_box', name: 'add box icon' },
  { icon: 'add_circle', name: 'add circle icon' },
  { icon: 'add_circle_outline', name: 'add circle outline icon' },
  { icon: 'archive', name: 'archive icon' },
  { icon: 'backspace', name: 'backspace icon' },
  { icon: 'ballot', name: 'ballot icon' },
  { icon: 'block', name: 'block icon' },
  { icon: 'clear', name: 'clear icon' },
  { icon: 'create', name: 'create icon' },
  { icon: 'delete_sweep', name: 'delete sweep icon' },
  { icon: 'drafts', name: 'drafts icon' },
  { icon: 'file_copy', name: 'file copy icon' },
  { icon: 'filter_list', name: 'filter list icon' },
  { icon: 'flag', name: 'flag icon' },
  { icon: 'font_download', name: 'font download icon' },
  { icon: 'forward', name: 'forward icon' },
  { icon: 'gesture', name: 'gesture icon' },
  { icon: 'how_to_reg', name: 'how to reg icon' },
  { icon: 'how_to_vote', name: 'how to vote icon' },
  { icon: 'inbox', name: 'inbox icon' },
  { icon: 'link', name: 'link icon' },
  { icon: 'link_off', name: 'link off icon' },
  { icon: 'low_priority', name: 'low priority icon' },
  { icon: 'mail', name: 'mail icon' },
  { icon: 'markunread', name: 'markunread icon' },
  { icon: 'move_to_inbox', name: 'move to inbox icon' },
  { icon: 'next_week', name: 'next week icon' },
  { icon: 'outlined_flag', name: 'outlined flag icon' },
  { icon: 'redo', name: 'redo icon' },
  { icon: 'remove', name: 'remove icon' },
  { icon: 'remove_circle', name: 'remove circle icon' },
  { icon: 'remove_circle_outline', name: 'remove circle outline icon' },
  { icon: 'reply', name: 'reply icon' },
  { icon: 'reply_all', name: 'reply all icon' },
  { icon: 'report', name: 'report icon' },
  { icon: 'report_off', name: 'report off icon' },
  { icon: 'save', name: 'save icon' },
  { icon: 'save_alt', name: 'save alt icon' },
  { icon: 'select_all', name: 'select all icon' },
  { icon: 'send', name: 'send icon' },
  { icon: 'sort', name: 'sort icon' },
  { icon: 'text_format', name: 'text format icon' },
  { icon: 'unarchive', name: 'unarchive icon' },
  { icon: 'undo', name: 'undo icon' },
  { icon: 'waves', name: 'waves icon' },
  { icon: 'weekend', name: 'weekend icon' },
  { icon: 'where_to_vote', name: 'where to vote icon' },
  { icon: 'access_alarm', name: 'access alarm icon' },
  { icon: 'access_alarms', name: 'access alarms icon' },
  { icon: 'access_time', name: 'access time icon' },
  { icon: 'add_alarm', name: 'add alarm icon' },
  { icon: 'add_to_home_screen', name: 'add to home screen icon' },
  { icon: 'airplanemode_active', name: 'airplanemode active icon' },
  { icon: 'airplanemode_inactive', name: 'airplanemode inactive icon' },
  { icon: 'battery_alert', name: 'battery alert icon' },
  { icon: 'battery_charging_full', name: 'battery charging full icon' },
  { icon: 'battery_full', name: 'battery full icon' },
  { icon: 'battery_std', name: 'battery std icon' },
  { icon: 'battery_unknown', name: 'battery unknown icon' },
  { icon: 'bluetooth', name: 'bluetooth icon' },
  { icon: 'bluetooth_connected', name: 'bluetooth connected icon' },
  { icon: 'bluetooth_disabled', name: 'bluetooth disabled icon' },
  { icon: 'bluetooth_searching', name: 'bluetooth searching icon' },
  { icon: 'brightness_auto', name: 'brightness auto icon' },
  { icon: 'brightness_high', name: 'brightness high icon' },
  { icon: 'brightness_low', name: 'brightness low icon' },
  { icon: 'brightness_medium', name: 'brightness medium icon' },
  { icon: 'data_usage', name: 'data usage icon' },
  { icon: 'developer_mode', name: 'developer mode icon' },
  { icon: 'devices', name: 'devices icon' },
  { icon: 'dvr', name: 'dvr icon' },
  { icon: 'gps_fixed', name: 'gps fixed icon' },
  { icon: 'gps_not_fixed', name: 'gps not fixed icon' },
  { icon: 'gps_off', name: 'gps off icon' },
  { icon: 'graphic_eq', name: 'graphic eq icon' },
  { icon: 'location_disabled', name: 'location disabled icon' },
  { icon: 'location_searching', name: 'location searching icon' },
  { icon: 'mobile_friendly', name: 'mobile friendly icon' },
  { icon: 'mobile_off', name: 'mobile off icon' },
  { icon: 'network_cell', name: 'network cell icon' },
  { icon: 'network_wifi', name: 'network wifi icon' },
  { icon: 'nfc', name: 'nfc icon' },
  { icon: 'screen_lock_landscape', name: 'screen lock landscape icon' },
  { icon: 'screen_lock_portrait', name: 'screen lock portrait icon' },
  { icon: 'screen_lock_rotation', name: 'screen lock rotation icon' },
  { icon: 'screen_rotation', name: 'screen rotation icon' },
  { icon: 'sd_storage', name: 'sd storage icon' },
  { icon: 'settings_system_daydream', name: 'settings system daydream icon' },
  { icon: 'signal_cellular_4_bar', name: 'signal cellular 4 bar icon' },
  { icon: 'signal_cellular_alt', name: 'signal cellular alt icon' },
  {
    icon: 'signal_cellular_connected_no_internet_4_bar',
    name: ' signal cellular connected no internet 4 bar icon ',
  },
  { icon: 'signal_cellular_no_sim', name: 'signal cellular no sim icon' },
  { icon: 'signal_cellular_null', name: 'signal cellular null icon' },
  { icon: 'signal_cellular_off', name: 'signal cellular off icon' },
  { icon: 'signal_wifi_4_bar', name: 'signal wifi 4 bar icon' },
  { icon: 'signal_wifi_4_bar_lock', name: 'signal wifi 4 bar lock icon' },
  { icon: 'signal_wifi_off', name: 'signal wifi off icon' },
  { icon: 'storage', name: 'storage icon' },
  { icon: 'usb', name: 'usb icon' },
  { icon: 'wallpaper', name: 'wallpaper icon' },
  { icon: 'widgets', name: 'widgets icon' },
  { icon: 'wifi_lock', name: 'wifi lock icon' },
  { icon: 'wifi_tethering', name: 'wifi tethering icon' },
  { icon: 'add_comment', name: 'add comment icon' },
  { icon: 'attach_file', name: 'attach file icon' },
  { icon: 'attach_money', name: 'attach money icon' },
  { icon: 'bar_chart', name: 'bar chart icon' },
  { icon: 'border_all', name: 'border all icon' },
  { icon: 'border_bottom', name: 'border bottom icon' },
  { icon: 'border_clear', name: 'border clear icon' },
  { icon: 'border_color', name: 'border color icon' },
  { icon: 'border_horizontal', name: 'border horizontal icon' },
  { icon: 'border_inner', name: 'border inner icon' },
  { icon: 'border_left', name: 'border left icon' },
  { icon: 'border_outer', name: 'border outer icon' },
  { icon: 'border_right', name: 'border right icon' },
  { icon: 'border_style', name: 'border style icon' },
  { icon: 'border_top', name: 'border top icon' },
  { icon: 'border_vertical', name: 'border vertical icon' },
  { icon: 'bubble_chart', name: 'bubble chart icon' },
  { icon: 'drag_handle', name: 'drag handle icon' },
  { icon: 'format_align_center', name: 'format align center icon' },
  { icon: 'format_align_justify', name: 'format align justify icon' },
  { icon: 'format_align_left', name: 'format align left icon' },
  { icon: 'format_align_right', name: 'format align right icon' },
  { icon: 'format_bold', name: 'format bold icon' },
  { icon: 'format_clear', name: 'format clear icon' },
  { icon: 'format_color_fill', name: 'format color fill icon' },
  { icon: 'format_color_reset', name: 'format color reset icon' },
  { icon: 'format_color_text', name: 'format color text icon' },
  { icon: 'format_indent_decrease', name: 'format indent decrease icon' },
  { icon: 'format_indent_increase', name: 'format indent increase icon' },
  { icon: 'format_italic', name: 'format italic icon' },
  { icon: 'format_line_spacing', name: 'format line spacing icon' },
  { icon: 'format_list_bulleted', name: 'format list bulleted icon' },
  { icon: 'format_list_numbered', name: 'format list numbered icon' },
  { icon: 'format_list_numbered_rtl', name: 'format list numbered rtl icon' },
  { icon: 'format_paint', name: 'format paint icon' },
  { icon: 'format_quote', name: 'format quote icon' },
  { icon: 'format_shapes', name: 'format shapes icon' },
  { icon: 'format_size', name: 'format size icon' },
  { icon: 'format_strikethrough', name: 'format strikethrough icon' },
  {
    icon: 'format_textdirection_l_to_r',
    name: 'format textdirection l to r icon',
  },
  {
    icon: 'format_textdirection_r_to_l',
    name: 'format textdirection r to l icon',
  },
  { icon: 'format_underlined', name: 'format underlined icon' },
  { icon: 'functions', name: 'functions icon' },
  { icon: 'highlight', name: 'highlight icon' },
  { icon: 'insert_chart', name: 'insert chart icon' },
  { icon: 'insert_chart_outlined', name: 'insert chart outlined icon' },
  { icon: 'insert_comment', name: 'insert comment icon' },
  { icon: 'insert_drive_file', name: 'insert drive file icon' },
  { icon: 'insert_emoticon', name: 'insert emoticon icon' },
  { icon: 'insert_invitation', name: 'insert invitation icon' },
  { icon: 'insert_link', name: 'insert link icon' },
  { icon: 'insert_photo', name: 'insert photo icon' },
  { icon: 'linear_scale', name: 'linear scale icon' },
  { icon: 'merge_type', name: 'merge type icon' },
  { icon: 'mode_comment', name: 'mode comment icon' },
  { icon: 'monetization_on', name: 'monetization on icon' },
  { icon: 'money_off', name: 'money off icon' },
  { icon: 'multiline_chart', name: 'multiline chart icon' },
  { icon: 'notes', name: 'notes icon' },
  { icon: 'pie_chart', name: 'pie chart icon' },
  { icon: 'publish', name: 'publish icon' },
  { icon: 'scatter_plot', name: 'scatter plot icon' },
  { icon: 'score', name: 'score icon' },
  { icon: 'short_text', name: 'short text icon' },
  { icon: 'show_chart', name: 'show chart icon' },
  { icon: 'space_bar', name: 'space bar icon' },
  { icon: 'strikethrough_s', name: 'strikethrough s icon' },
  { icon: 'table_chart', name: 'table chart icon' },
  { icon: 'text_fields', name: 'text fields icon' },
  { icon: 'title', name: 'title icon' },
  { icon: 'vertical_align_bottom', name: 'vertical align bottom icon' },
  { icon: 'vertical_align_center', name: 'vertical align center icon' },
  { icon: 'vertical_align_top', name: 'vertical align top icon' },
  { icon: 'wrap_text', name: 'wrap text icon' },
  { icon: 'attachment', name: 'attachment icon' },
  { icon: 'cloud', name: 'cloud icon' },
  { icon: 'cloud_circle', name: 'cloud circle icon' },
  { icon: 'cloud_done', name: 'cloud done icon' },
  { icon: 'cloud_download', name: 'cloud download icon' },
  { icon: 'cloud_off', name: 'cloud off icon' },
  { icon: 'cloud_queue', name: 'cloud queue icon' },
  { icon: 'cloud_upload', name: 'cloud upload icon' },
  { icon: 'create_new_folder', name: 'create new folder icon' },
  { icon: 'folder', name: 'folder icon' },
  { icon: 'folder_open', name: 'folder open icon' },
  { icon: 'folder_shared', name: 'folder shared icon' },
  { icon: 'cast', name: 'cast icon' },
  { icon: 'cast_connected', name: 'cast connected icon' },
  { icon: 'computer', name: 'computer icon' },
  { icon: 'desktop_mac', name: 'desktop mac icon' },
  { icon: 'desktop_windows', name: 'desktop windows icon' },
  { icon: 'developer_board', name: 'developer board icon' },
  { icon: 'device_hub', name: 'device hub icon' },
  { icon: 'device_unknown', name: 'device unknown icon' },
  { icon: 'devices_other', name: 'devices other icon' },
  { icon: 'dock', name: 'dock icon' },
  { icon: 'gamepad', name: 'gamepad icon' },
  { icon: 'headset', name: 'headset icon' },
  { icon: 'headset_mic', name: 'headset mic icon' },
  { icon: 'keyboard', name: 'keyboard icon' },
  { icon: 'keyboard_arrow_down', name: 'keyboard arrow down icon' },
  { icon: 'keyboard_arrow_left', name: 'keyboard arrow left icon' },
  { icon: 'keyboard_arrow_right', name: 'keyboard arrow right icon' },
  { icon: 'keyboard_arrow_up', name: 'keyboard arrow up icon' },
  { icon: 'keyboard_backspace', name: 'keyboard backspace icon' },
  { icon: 'keyboard_capslock', name: 'keyboard capslock icon' },
  { icon: 'keyboard_hide', name: 'keyboard hide icon' },
  { icon: 'keyboard_return', name: 'keyboard return icon' },
  { icon: 'keyboard_tab', name: 'keyboard tab icon' },
  { icon: 'keyboard_voice', name: 'keyboard voice icon' },
  { icon: 'laptop', name: 'laptop icon' },
  { icon: 'laptop_chromebook', name: 'laptop chromebook icon' },
  { icon: 'laptop_mac', name: 'laptop mac icon' },
  { icon: 'laptop_windows', name: 'laptop windows icon' },
  { icon: 'memory', name: 'memory icon' },
  { icon: 'mouse', name: 'mouse icon' },
  { icon: 'phone_android', name: 'phone android icon' },
  { icon: 'phone_iphone', name: 'phone iphone icon' },
  { icon: 'phonelink', name: 'phonelink icon' },
  { icon: 'phonelink_off', name: 'phonelink off icon' },
  { icon: 'power_input', name: 'power input icon' },
  { icon: 'router', name: 'router icon' },
  { icon: 'scanner', name: 'scanner icon' },
  { icon: 'security', name: 'security icon' },
  { icon: 'sim_card', name: 'sim card icon' },
  { icon: 'smartphone', name: 'smartphone icon' },
  { icon: 'speaker', name: 'speaker icon' },
  { icon: 'speaker_group', name: 'speaker group icon' },
  { icon: 'tablet', name: 'tablet icon' },
  { icon: 'tablet_android', name: 'tablet android icon' },
  { icon: 'tablet_mac', name: 'tablet mac icon' },
  { icon: 'toys', name: 'toys icon' },
  { icon: 'tv', name: 'tv icon' },
  { icon: 'videogame_asset', name: 'videogame asset icon' },
  { icon: 'watch', name: 'watch icon' },
  { icon: 'add_a_photo', name: 'add a photo icon' },
  { icon: 'add_photo_alternate', name: 'add photo alternate icon' },
  { icon: 'add_to_photos', name: 'add to photos icon' },
  { icon: 'adjust', name: 'adjust icon' },
  { icon: 'assistant', name: 'assistant icon' },
  { icon: 'assistant_photo', name: 'assistant photo icon' },
  { icon: 'audiotrack', name: 'audiotrack icon' },
  { icon: 'blur_circular', name: 'blur circular icon' },
  { icon: 'blur_linear', name: 'blur linear icon' },
  { icon: 'blur_off', name: 'blur off icon' },
  { icon: 'blur_on', name: 'blur on icon' },
  { icon: 'brightness_1', name: 'brightness 1 icon' },
  { icon: 'brightness_2', name: 'brightness 2 icon' },
  { icon: 'brightness_3', name: 'brightness 3 icon' },
  { icon: 'brightness_4', name: 'brightness 4 icon' },
  { icon: 'brightness_5', name: 'brightness 5 icon' },
  { icon: 'brightness_6', name: 'brightness 6 icon' },
  { icon: 'brightness_7', name: 'brightness 7 icon' },
  { icon: 'broken_image', name: 'broken image icon' },
  { icon: 'brush', name: 'brush icon' },
  { icon: 'burst_mode', name: 'burst mode icon' },
  { icon: 'camera', name: 'camera icon' },
  { icon: 'camera_alt', name: 'camera alt icon' },
  { icon: 'camera_front', name: 'camera front icon' },
  { icon: 'camera_rear', name: 'camera rear icon' },
  { icon: 'camera_roll', name: 'camera roll icon' },
  { icon: 'center_focus_strong', name: 'center focus strong icon' },
  { icon: 'center_focus_weak', name: 'center focus weak icon' },
  { icon: 'collections', name: 'collections icon' },
  { icon: 'collections_bookmark', name: 'collections bookmark icon' },
  { icon: 'color_lens', name: 'color lens icon' },
  { icon: 'colorize', name: 'colorize icon' },
  { icon: 'compare', name: 'compare icon' },
  { icon: 'control_point', name: 'control point icon' },
  { icon: 'control_point_duplicate', name: 'control pointduplicate icon' },
  { icon: 'crop', name: 'crop icon' },
  { icon: 'crop_16_9', name: 'crop 16 9 icon' },
  { icon: 'crop_3_2', name: 'crop 3 2 icon' },
  { icon: 'crop_5_4', name: 'crop 5 4 icon' },
  { icon: 'crop_7_5', name: 'crop 7 5 icon' },
  { icon: 'crop_din', name: 'crop din icon' },
  { icon: 'crop_free', name: 'crop free icon' },
  { icon: 'crop_landscape', name: 'crop landscape icon' },
  { icon: 'crop_original', name: 'crop original icon' },
  { icon: 'crop_portrait', name: 'crop portrait icon' },
  { icon: 'crop_rotate', name: 'crop rotate icon' },
  { icon: 'crop_square', name: 'crop square icon' },
  { icon: 'dehaze', name: 'dehaze icon' },
  { icon: 'details', name: 'details icon' },
  { icon: 'edit', name: 'edit icon' },
  { icon: 'exposure', name: 'exposure icon' },
  { icon: 'exposure_neg_1', name: 'exposure neg 1 icon' },
  { icon: 'exposure_neg_2', name: 'exposure neg 2 icon' },
  { icon: 'exposure_plus_1', name: 'exposure plus 1 icon' },
  { icon: 'exposure_plus_2', name: 'exposure plus 2 icon' },
  { icon: 'exposure_zero', name: 'exposure zero icon' },
  { icon: 'filter', name: 'filter icon' },
  { icon: 'filter_1', name: 'filter 1 icon' },
  { icon: 'filter_2', name: 'filter 2 icon' },
  { icon: 'filter_3', name: 'filter 3 icon' },
  { icon: 'filter_4', name: 'filter 4 icon' },
  { icon: 'filter_5', name: 'filter 5 icon' },
  { icon: 'filter_6', name: 'filter 6 icon' },
  { icon: 'filter_7', name: 'filter 7 icon' },
  { icon: 'filter_8', name: 'filter 8 icon' },
  { icon: 'filter_9', name: 'filter 9 icon' },
  { icon: 'filter_9_plus', name: 'filter 9 plus icon' },
  { icon: 'filter_b_and_w', name: 'filter b and w icon' },
  { icon: 'filter_center_focus', name: 'filter center focus icon' },
  { icon: 'filter_drama', name: 'filter drama icon' },
  { icon: 'filter_frames', name: 'filter frames icon' },
  { icon: 'filter_hdr', name: 'filter hdr icon' },
  { icon: 'filter_none', name: 'filter none icon' },
  { icon: 'filter_tilt_shift', name: 'filter tilt shift icon' },
  { icon: 'filter_vintage', name: 'filter vintage icon' },
  { icon: 'flare', name: 'flare icon' },
  { icon: 'flash_auto', name: 'flash auto icon' },
  { icon: 'flash_off', name: 'flash off icon' },
  { icon: 'flash_on', name: 'flash on icon' },
  { icon: 'flip', name: 'flip icon' },
  { icon: 'gradient', name: 'gradient icon' },
  { icon: 'grain', name: 'grain icon' },
  { icon: 'grid_off', name: 'grid off icon' },
  { icon: 'grid_on', name: 'grid on icon' },
  { icon: 'hdr_off', name: 'hdr off icon' },
  { icon: 'hdr_on', name: 'hdr on icon' },
  { icon: 'hdr_strong', name: 'hdr strong icon' },
  { icon: 'hdr_weak', name: 'hdr weak icon' },
  { icon: 'healing', name: 'healing icon' },
  { icon: 'image', name: 'image icon' },
  { icon: 'image_aspect_ratio', name: 'image aspect ratio icon' },
  { icon: 'image_search', name: 'image search icon' },
  { icon: 'iso', name: 'iso icon' },
  { icon: 'landscape', name: 'landscape icon' },
  { icon: 'leak_add', name: 'leak add icon' },
  { icon: 'leak_remove', name: 'leak remove icon' },
  { icon: 'lens', name: 'lens icon' },
  { icon: 'linked_camera', name: 'linked camera icon' },
  { icon: 'looks', name: 'looks icon' },
  { icon: 'looks_3', name: 'looks 3 icon' },
  { icon: 'looks_4', name: 'looks 4 icon' },
  { icon: 'looks_5', name: 'looks 5 icon' },
  { icon: 'looks_6', name: 'looks 6 icon' },
  { icon: 'looks_one', name: 'looks one icon' },
  { icon: 'looks_two', name: 'looks two icon' },
  { icon: 'loupe', name: 'loupe icon' },
  { icon: 'monochrome_photos', name: 'monochrome photos icon' },
  { icon: 'movie_creation', name: 'movie creation icon' },
  { icon: 'movie_filter', name: 'movie filter icon' },
  { icon: 'music_note', name: 'music note icon' },
  { icon: 'music_off', name: 'music off icon' },
  { icon: 'nature', name: 'nature icon' },
  { icon: 'nature_people', name: 'nature people icon' },
  { icon: 'navigate_before', name: 'navigate before icon' },
  { icon: 'navigate_next', name: 'navigate next icon' },
  { icon: 'palette', name: 'palette icon' },
  { icon: 'panorama', name: 'panorama icon' },
  { icon: 'panorama_fish_eye', name: 'panorama fish eye icon' },
  { icon: 'panorama_horizontal', name: 'panorama horizontal icon' },
  { icon: 'panorama_vertical', name: 'panorama vertical icon' },
  { icon: 'panorama_wide_angle', name: 'panorama wide angle icon' },
  { icon: 'photo', name: 'photo icon' },
  { icon: 'photo_album', name: 'photo album icon' },
  { icon: 'photo_camera', name: 'photo camera icon' },
  { icon: 'photo_filter', name: 'photo filter icon' },
  { icon: 'photo_library', name: 'photo library icon' },
  { icon: 'photo_size_select_actual', name: 'photo size selectactual icon' },
  { icon: 'photo_size_select_large', name: 'photo size selectlarge icon' },
  { icon: 'photo_size_select_small', name: 'photo size selectsmall icon' },
  { icon: 'picture_as_pdf', name: 'picture as pdf icon' },
  { icon: 'portrait', name: 'portrait icon' },
  { icon: 'remove_red_eye', name: 'remove red eye icon' },
  { icon: 'rotate_90_degrees_ccw', name: 'rotate 90 degrees ccwicon' },
  { icon: 'rotate_left', name: 'rotate left icon' },
  { icon: 'rotate_right', name: 'rotate right icon' },
  { icon: 'shutter_speed', name: 'shutter speed icon' },
  { icon: 'slideshow', name: 'slideshow icon' },
  { icon: 'straighten', name: 'straighten icon' },
  { icon: 'style', name: 'style icon' },
  { icon: 'switch_camera', name: 'switch camera icon' },
  { icon: 'switch_video', name: 'switch video icon' },
  { icon: 'tag_faces', name: 'tag faces icon' },
  { icon: 'texture', name: 'texture icon' },
  { icon: 'timelapse', name: 'timelapse icon' },
  { icon: 'timer', name: 'timer icon' },
  { icon: 'timer_10', name: 'timer 10 icon' },
  { icon: 'timer_3', name: 'timer 3 icon' },
  { icon: 'timer_off', name: 'timer off icon' },
  { icon: 'tonality', name: 'tonality icon' },
  { icon: 'transform', name: 'transform icon' },
  { icon: 'tune', name: 'tune icon' },
  { icon: 'view_comfy', name: 'view comfy icon' },
  { icon: 'view_compact', name: 'view compact icon' },
  { icon: 'vignette', name: 'vignette icon' },
  { icon: 'wb_auto', name: 'wb auto icon' },
  { icon: 'wb_cloudy', name: 'wb cloudy icon' },
  { icon: 'wb_incandescent', name: 'wb incandescent icon' },
  { icon: 'wb_iridescent', name: 'wb iridescent icon' },
  { icon: 'wb_sunny', name: 'wb sunny icon' },
  { icon: '360', name: '360 icon' },
  { icon: 'add_location', name: 'add location icon' },
  { icon: 'atm', name: 'atm icon' },
  { icon: 'beenhere', name: 'beenhere icon' },
  { icon: 'category', name: 'category icon' },
  { icon: 'compass_calibration', name: 'compass calibration icon' },
  { icon: 'departure_board', name: 'departure board icon' },
  { icon: 'directions', name: 'directions icon' },
  { icon: 'directions_bike', name: 'directions bike icon' },
  { icon: 'directions_boat', name: 'directions boat icon' },
  { icon: 'directions_bus', name: 'directions bus icon' },
  { icon: 'directions_car', name: 'directions car icon' },
  { icon: 'directions_railway', name: 'directions railway icon' },
  { icon: 'directions_run', name: 'directions run icon' },
  { icon: 'directions_subway', name: 'directions subway icon' },
  { icon: 'directions_transit', name: 'directions transit icon' },
  { icon: 'directions_walk', name: 'directions walk icon' },
  { icon: 'edit_attributes', name: 'edit attributes icon' },
  { icon: 'edit_location', name: 'edit location icon' },
  { icon: 'ev_station', name: 'ev station icon' },
  { icon: 'fastfood', name: 'fastfood icon' },
  { icon: 'flight', name: 'flight icon' },
  { icon: 'hotel', name: 'hotel icon' },
  { icon: 'layers', name: 'layers icon' },
  { icon: 'layers_clear', name: 'layers clear icon' },
  { icon: 'local_activity', name: 'local activity icon' },
  { icon: 'local_airport', name: 'local airport icon' },
  { icon: 'local_atm', name: 'local atm icon' },
  { icon: 'local_bar', name: 'local bar icon' },
  { icon: 'local_cafe', name: 'local cafe icon' },
  { icon: 'local_car_wash', name: 'local car wash icon' },
  { icon: 'local_convenience_store', name: 'local convenience  store icon' },
  { icon: 'local_dining', name: 'local dining icon' },
  { icon: 'local_drink', name: 'local drink icon' },
  { icon: 'local_florist', name: 'local florist icon' },
  { icon: 'local_gas_station', name: 'local gas station icon' },
  { icon: 'local_grocery_store', name: 'local grocery store icon' },
  { icon: 'local_hospital', name: 'local hospital icon' },
  { icon: 'local_hotel', name: 'local hotel icon' },
  { icon: 'local_laundry_service', name: 'local laundry service  icon' },
  { icon: 'local_library', name: 'local library icon' },
  { icon: 'local_mall', name: 'local mall icon' },
  { icon: 'local_movies', name: 'local movies icon' },
  { icon: 'local_offer', name: 'local offer icon' },
  { icon: 'local_parking', name: 'local parking icon' },
  { icon: 'local_pharmacy', name: 'local pharmacy icon' },
  { icon: 'local_phone', name: 'local phone icon' },
  { icon: 'local_pizza', name: 'local pizza icon' },
  { icon: 'local_play', name: 'local play icon' },
  { icon: 'local_post_office', name: 'local post office icon' },
  { icon: 'local_printshop', name: 'local printshop icon' },
  { icon: 'local_see', name: 'local see icon' },
  { icon: 'local_shipping', name: 'local shipping icon' },
  { icon: 'local_taxi', name: 'local taxi icon' },
  { icon: 'map', name: 'map icon' },
  { icon: 'money', name: 'money icon' },
  { icon: 'my_location', name: 'my location icon' },
  { icon: 'navigation', name: 'navigation icon' },
  { icon: 'near_me', name: 'near me icon' },
  { icon: 'not_listed_location', name: 'not listed location icon' },
  { icon: 'person_pin', name: 'person pin icon' },
  { icon: 'person_pin_circle', name: 'person pin circle icon' },
  { icon: 'pin_drop', name: 'pin drop icon' },
  { icon: 'place', name: 'place icon' },
  { icon: 'rate_review', name: 'rate review icon' },
  { icon: 'restaurant', name: 'restaurant icon' },
  { icon: 'restaurant_menu', name: 'restaurant menu icon' },
  { icon: 'satellite', name: 'satellite icon' },
  { icon: 'store_mall_directory', name: 'store mall directory icon' },
  { icon: 'streetview', name: 'streetview icon' },
  { icon: 'subway', name: 'subway icon' },
  { icon: 'terrain', name: 'terrain icon' },
  { icon: 'traffic', name: 'traffic icon' },
  { icon: 'train', name: 'train icon' },
  { icon: 'tram', name: 'tram icon' },
  {
    icon: 'transfer_within_a_station',
    name: 'transfer within a  station icon',
  },
  { icon: 'transit_enterexit', name: 'transit enterexit icon' },
  { icon: 'trip_origin', name: 'trip origin icon' },
  { icon: 'zoom_out_map', name: 'zoom out map icon' },
  { icon: 'apps', name: 'apps icon' },
  { icon: 'arrow_back', name: 'arrow back icon' },
  { icon: 'arrow_back_ios', name: 'arrow back ios icon' },
  { icon: 'arrow_downward', name: 'arrow downward icon' },
  { icon: 'arrow_drop_down', name: 'arrow drop down icon' },
  { icon: 'arrow_drop_down_circle', name: 'arrow drop down circle icon' },
  { icon: 'arrow_drop_up', name: 'arrow drop up icon' },
  { icon: 'arrow_forward', name: 'arrow forward icon' },
  { icon: 'arrow_forward_ios', name: 'arrow forward ios icon' },
  { icon: 'arrow_left', name: 'arrow left icon' },
  { icon: 'arrow_right', name: 'arrow right icon' },
  { icon: 'arrow_upward', name: 'arrow upward icon' },
  { icon: 'cancel', name: 'cancel icon' },
  { icon: 'check', name: 'check icon' },
  { icon: 'chevron_left', name: 'chevron left icon' },
  { icon: 'chevron_right', name: 'chevron right icon' },
  { icon: 'close', name: 'close icon' },
  { icon: 'expand_less', name: 'expand less icon' },
  { icon: 'expand_more', name: 'expand more icon' },
  { icon: 'first_page', name: 'first page icon' },
  { icon: 'fullscreen', name: 'fullscreen icon' },
  { icon: 'fullscreen_exit', name: 'fullscreen exit icon' },
  { icon: 'last_page', name: 'last page icon' },
  { icon: 'menu', name: 'menu icon' },
  { icon: 'more_horiz', name: 'more horiz icon' },
  { icon: 'more_vert', name: 'more vert icon' },
  { icon: 'refresh', name: 'refresh icon' },
  { icon: 'subdirectory_arrow_left', name: 'subdirectory arrow left icon' },
  { icon: 'subdirectory_arrow_right', name: 'subdirectory arrow right icon' },
  { icon: 'unfold_less', name: 'unfold less icon' },
  { icon: 'unfold_more', name: 'unfold more icon' },
  { icon: 'adb', name: 'adb icon' },
  { icon: 'airline_seat_flat', name: 'airline seat flat icon' },
  { icon: 'airline_seat_flat_angled', name: 'airline seat flat angled icon' },
  {
    icon: 'airline_seat_individual_suite',
    name: 'airline seat individual suite icon',
  },
  {
    icon: 'airline_seat_legroom_extra',
    name: 'airline seat legroom extra icon',
  },
  {
    icon: 'airline_seat_legroom_normal',
    name: 'airline seat legroom normal icon',
  },
  {
    icon: 'airline_seat_legroom_reduced',
    name: 'airline seat legroom reduced icon',
  },
  {
    icon: 'airline_seat_recline_extra',
    name: 'airline seat recline extra icon',
  },
  {
    icon: 'airline_seat_recline_normal',
    name: 'airline seat recline normal icon',
  },
  { icon: 'bluetooth_audio', name: 'bluetooth audio icon' },
  { icon: 'confirmation_number', name: 'confirmation number icon' },
  { icon: 'disc_full', name: 'disc full icon' },
  { icon: 'drive_eta', name: 'drive eta icon' },
  { icon: 'enhanced_encryption', name: 'enhanced encryption icon' },
  { icon: 'event_available', name: 'event available icon' },
  { icon: 'event_busy', name: 'event busy icon' },
  { icon: 'event_note', name: 'event note icon' },
  { icon: 'folder_special', name: 'folder special icon' },
  { icon: 'live_tv', name: 'live tv icon' },
  { icon: 'mms', name: 'mms icon' },
  { icon: 'more', name: 'more icon' },
  { icon: 'network_check', name: 'network check icon' },
  { icon: 'network_locked', name: 'network locked icon' },
  { icon: 'no_encryption', name: 'no encryption icon' },
  { icon: 'ondemand_video', name: 'ondemand video icon' },
  { icon: 'personal_video', name: 'personal video icon' },
  { icon: 'phone_bluetooth_speaker', name: 'phone bluetooth speaker icon' },
  { icon: 'phone_callback', name: 'phone callback icon' },
  { icon: 'phone_forwarded', name: 'phone forwarded icon' },
  { icon: 'phone_in_talk', name: 'phone in talk icon' },
  { icon: 'phone_locked', name: 'phone locked icon' },
  { icon: 'phone_missed', name: 'phone missed icon' },
  { icon: 'phone_paused', name: 'phone paused icon' },
  { icon: 'power', name: 'power icon' },
  { icon: 'power_off', name: 'power off icon' },
  { icon: 'priority_high', name: 'priority high icon' },
  { icon: 'sd_card', name: 'sd card icon' },
  { icon: 'sms', name: 'sms icon' },
  { icon: 'sms_failed', name: 'sms failed icon' },
  { icon: 'sync', name: 'sync icon' },
  { icon: 'sync_disabled', name: 'sync disabled icon' },
  { icon: 'sync_problem', name: 'sync problem icon' },
  { icon: 'system_update', name: 'system update icon' },
  { icon: 'tap_and_play', name: 'tap and play icon' },
  { icon: 'time_to_leave', name: 'time to leave icon' },
  { icon: 'tv_off', name: 'tv off icon' },
  { icon: 'vibration', name: 'vibration icon' },
  { icon: 'voice_chat', name: 'voice chat icon' },
  { icon: 'vpn_lock', name: 'vpn lock icon' },
  { icon: 'wc', name: 'wc icon' },
  { icon: 'wifi', name: 'wifi icon' },
  { icon: 'wifi_off', name: 'wifi off icon' },
  { icon: 'ac_unit', name: ' ac unit icon' },
  { icon: 'airport_shuttle', name: ' airport shuttle icon' },
  { icon: 'all_inclusive', name: ' all inclusive icon' },
  { icon: 'beach_access', name: ' beach access icon' },
  { icon: 'business_center', name: ' business center icon' },
  { icon: 'casino', name: ' casino icon' },
  { icon: 'child_care', name: ' child care icon' },
  { icon: 'child_friendly', name: ' child friendly icon' },
  { icon: 'fitness_center', name: ' fitness center icon' },
  { icon: 'free_breakfast', name: ' free breakfast icon' },
  { icon: 'golf_course', name: ' golf course icon' },
  { icon: 'hot_tub', name: ' hot tub icon' },
  { icon: 'kitchen', name: ' kitchen icon' },
  { icon: 'meeting_room', name: ' meeting room icon' },
  { icon: 'no_meeting_room', name: ' no meeting room icon' },
  { icon: 'pool', name: ' pool icon' },
  { icon: 'room_service', name: ' room service icon' },
  { icon: 'rv_hookup', name: ' rv hookup icon' },
  { icon: 'smoke_free', name: ' smoke free icon' },
  { icon: 'smoking_rooms', name: ' smoking rooms icon' },
  { icon: 'spa', name: ' spa icon' },
  { icon: 'check_box', name: ' check box icon' },
  { icon: 'check_box_outline_blank', name: ' check box outline blank icon' },
  { icon: 'indeterminate_check_box', name: ' indeterminate check box icon' },
  { icon: 'radio_button_checked', name: ' radio button checked icon' },
  { icon: 'radio_button_unchecked', name: ' radio button unchecked icon' },
  { icon: 'star', name: ' star icon' },
  { icon: 'star_border', name: ' star border icon' },
  { icon: 'star_half', name: ' star half icon' },
  { icon: 'add_alert', name: ' add alert icon' },
  { icon: 'error', name: ' error icon' },
  { icon: 'error_outline', name: ' error outline icon' },
  { icon: 'notification_important', name: ' notification important icon' },
  { icon: 'warning', name: ' warning icon' },
  { icon: 'cake', name: ' cake icon' },
  { icon: 'domain', name: ' domain icon' },
  { icon: 'group', name: ' group icon' },
  { icon: 'group_add', name: ' group add icon' },
  { icon: 'location_city', name: ' location city icon' },
  { icon: 'mood', name: ' mood icon' },
  { icon: 'mood_bad', name: ' mood bad icon' },
  { icon: 'notifications', name: ' notifications icon' },
  { icon: 'notifications_active', name: ' notifications active icon' },
  { icon: 'notifications_none', name: ' notifications none icon' },
  { icon: 'notifications_off', name: ' notifications off icon' },
  { icon: 'notifications_paused', name: ' notifications paused icon' },
  { icon: 'pages', name: ' pages icon' },
  { icon: 'party_mode', name: ' party mode icon' },
  { icon: 'people', name: ' people icon' },
  { icon: 'people_outline', name: ' people outline icon' },
  { icon: 'person', name: ' person icon' },
  { icon: 'person_add', name: ' person add icon' },
  { icon: 'person_outline', name: ' person outline icon' },
  { icon: 'plus_one', name: ' plus one icon' },
  { icon: 'poll', name: ' poll icon' },
  { icon: 'public', name: ' public icon' },
  { icon: 'school', name: ' school icon' },
  { icon: 'sentiment_dissatisfied', name: ' sentiment dissatisfied icon' },
  { icon: 'sentiment_satisfied', name: ' sentiment satisfied icon' },
  {
    icon: 'sentiment_very_dissatisfied',
    name: ' sentiment very dissatisfied icon',
  },
  { icon: 'sentiment_very_satisfied', name: ' sentiment very satisfied icon' },
  { icon: 'share', name: ' share icon' },
  { icon: 'thumb_down_alt', name: ' thumb down alt icon' },
  { icon: 'thumb_up_alt', name: ' thumb up alt icon' },
  { icon: 'whatshot', name: ' whatshot icon' },
];
